routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/dashboard');
});

Auth::routes([]);

Route::get('/home', function () {
    return redirect('/dashboard');
});

Route::group(['middleware' => 'auth'], function () {
    Route::get('/dashboard', 'DashboardController@index')->name('home');
    Route::get('/siswa/export_excel', 'SiswaController@export_excel')->name('siswa-export-excel');
    Route::get('/siswa/export_pdf', 'SiswaController@export_pdf')->name('siswa-export-pdf');
    Route::resource('/siswa', 'SiswaController');
    Route::resource('/kelas', 'KelasController');
    Route::get('/tabungan', 'TabunganController@index')->name('tabungan');
    Route::resource('/transaksi', 'TransaksiController');
    Route::resource('/buku', 'BukuController');
    Route::resource('/pinjaman', 'PinjamanController');
    Route::get('/transaksi/rekap', 'TabunganController@index')->name('transaksi.rekap');
    Route::get('/panduan', 'PanduanController@index')->name('panduan');
    Route::get('/profile', 'HomeController@profile')->name('profile');
    Route::get('/user', 'HomeController@user')->name('user');
    Route::post('/profile/store', 'HomeController@profile_update')->name('profile.store');

    Route::get('/user/export_pdf', 'HomeController@user_export_pdf')->name('user-export-pdf');
});

app/Transaksi.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use DB;

class Transaksi extends Model
{
    protected $guarded = [];

    public function student() {
    	return $this->belongsTo('App\Kelas', 'kelas_id');
    }

    public function savings() {
    	return $this->belongsTo('App\Saving', 'saving_id');
    }

    // public function kelas() {
    // 	return $this->belongsTo('App\Kelas');
    // }

    public function siswa()
    {
        return $this->belongsTo('App\Siswa', 'siswa_id', 'induk');
    }

    
}

app/Http/Controllers/TransaksiController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;
use App\Transaksi;
use App\Kelas;
use App\Siswa;
use App\Saving;
use App\Buku;

class TransaksiController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $siswas = Siswa::with('transactions')->Paginate(10);
        $data = Transaksi::paginate(10);
        // dd($siswas);
        // dd($siswas);
        return view('admin.transaksi.index', compact('siswas', 'data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data = Transaksi::all();
        $buku = Buku::all();
        $siswa = Siswa::all();
        // $siswas = Siswa::with('transactions')->get();
        return view('admin.transaksi.add', compact('buku', 'siswa', 'data'));
    }

    public function rekap()
    {
        //
    }


    public function store(Request $request)
    {
        $student = Siswa::where('induk', $request->input('induk'))->first();
        if (empty($student)) {
            $message = 'Siswa dengan nomor induk tersebut ' . $request->input('id') . ' tidak ditemukan.';
            return redirect()->back()->with('success', $message);
        } else {
            if (($request->input('type') == 0) && ($request->input('amount') > $student->saldo)) {
                $message = "Saldo tidak cukup!";
                return redirect('transaksi/create')->with('success', $message);
            } elseif (($request->input('type') == 0)) {


                $transaksi_created = Transaksi::create([
                    'siswa_id' => $request->induk,
                    'amount' => $request->amount,
                    'saving_id' => 0,
                    'type' => $request->type,
                ]);

                $total = $student->saldo - $request->amount;
                DB::table('siswas')->where('induk', $request->induk)->update([
                    'saldo' => $total,
                ]);



                // nama transaksi
                $namaTransaksi = "";
                if ($request->input('type') == 1) {
                    $namaTransaksi = "Setor";
                } else {
                    $namaTransaksi = "Tarik";
                }
                $message = "Informasi Nasabah | 
				No Induk = " . $student->id . " |
				Waktu Transaksi = " . date('d M Y H:i:s') . " |
				nama = " . $student->name . " |
				tipe = " . $namaTransaksi . " |
				saldo = " . $this->rupiah($request->input('amount')) . " |
				total saldo = " . $this->rupiah($total) . " | ";
                return redirect()->back()->with('success', $message);
            } else {
                $transaksi_created = Transaksi::create([
                    'siswa_id' => $request->induk,
                    'amount' => $request->amount,
                    'saving_id' => 1,
                    'type' => $request->type,
                ]);

                $total = $student->saldo + $request->amount;
                DB::table('siswas')->where('induk', $request->induk)->update([
                    'saldo' => $total,
                ]);



                // nama transaksi
                $namaTransaksi = "";
                if ($request->input('type') == 1) {
                    $namaTransaksi = "Setor";
                } else {
                    $namaTransaksi = "Tarik";
                }
                $message = "Informasi Nasabah <br> 
				No Induk = " . $student->id . " |
				Waktu Transaksi = " . date('d M Y H:i:s') . " |
				nama = " . $student->nama . " |
				tipe = " . $namaTransaksi . " |
				saldo = " . $this->rupiah($request->input('amount')) . " |
				total saldo = " . $this->rupiah($total) . " | ";
                return redirect()->back()->with('success', $message);
            }
        }
    }

    public function rupiah($angka)
    {

        $hasil_rupiah = number_format($angka, 0, '.', ',');
        return $hasil_rupiah;
    }

    public function show(Transaksi $transaksi)
    {
        //
    }


    public function edit(Transaksi $transaksi)
    {
        //
    }


    public function update(Request $request, Transaksi $transaksi)
    {
        //
    }


    public function destroy(Transaksi $transaksi)
    {
        //
    }
}

resources/views/admin/transaksi/add.blade.php
<?php
function rupiah($angka)
{

    $hasil_rupiah = number_format($angka, 0, '.', ',');
    return $hasil_rupiah;
}
?>
@extends('backend.master')
@section('title', 'Pinjaman Baru')
@section('sub-judul', 'Mahasiswa')

@section('button')

@endsection
@section('content')
@if(count($errors) >0)
@foreach($errors->all() as $error )
<div class="alert alert-danger" role="alert">
    {{ $error }}
</div>
@endforeach
@endif

@if(Session::has('success'))
<div class="alert alert-success alert-dismissible fade show" role="alert">
    <strong>{{ Session('success') }}</strong>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
@endif
<div class="row">
    <div class="col-lg-12">
        <div class="card m-b-20">
            <div class="card-body">

                <h4 class="mt-0 header-title">Pinjaman Baru</h4>

                <p>
                    <a class="btn btn-warning btn-sm waves-effect waves-light" style="float: right!important;" data-toggle="collapse" href="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
                        -
                    </a>
                </p>
                <br><br>
                <div class="collapse show" id="collapseExample">
                    <div class="card card-body mb-0">
                        <form action="{{route('transaksi.store')}}" method="POST">
                            @csrf
                            <div class="form-group">
                                <label>Mahasiswa</label>
                                <select class="form-control" name="siswa" required="">
                                    <option selected="" disabled="">-- Pilih Mahasiswa --</option>
                                    @foreach($siswa as $b)
                                    <option value="{{$b->id}}">{{$b->nama}}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <label>Buku</label>
                                <select class="form-control" name="buku" required="">
                                    <option selected="" disabled="">-- Pilih Buku --</option>
                                    @foreach($buku as $b)
                                    <option value="{{$b->id}}">{{$b->nama}}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="box-footer">
                                <input type="submit" class="btn btn-primary pull-right" value="Tambah Transaksi">
                            </div>
                        </form>
                    </div>

                </div>

            </div>
        </div>
    </div> <!-- end col -->
</div>
<script type="text/javascript">
    var app = new Vue({
        el: '#app',
        data: {
            saldo: 0
        }
    })
</script>
<script type="text/javascript">
    Vue.filter('currency', function(val) {
        return accounting.formatMoney(val, "Rp. ", 0, ".", ",");;
    })
</script>

@endsection
@section('page_css')
<!-- DataTables -->
<link rel="stylesheet" href="{{ asset('dist/plugins/datatables/dataTables.bootstrap4.min.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('dist/plugins/datatables/buttons.bootstrap4.min.css') }}" />
<!-- Responsive datatable examples -->
<link href="{{ asset('dist/plugins/datatables/responsive.bootstrap4.min.css') }}" rel="stylesheet" type="text/css" />
<script src="{{ asset('dist/assets/js/vue.js') }}"></script>
<script src="{{ asset('dist/assets/js/accounting.min.js') }}"></script>


<script src="{{ asset('dist/assets/js/vue.js') }}"></script>
<script src="{{ asset('dist/assets/js/accounting.min.js') }}"></script>

<style type="text/css">
    .noline {
        display: inline;
        margin: 0px;
        padding: 0px;
    }

    input[type=number]::-webkit-inner-spin-button,
    input[type=number]::-webkit-outer-spin-button {
        -webkit-appearance: none;
        margin: 0;
    }
</style>
@endsection

@section('page_js')
<!-- DataTables -->
<!-- Required datatable js -->
<script src="{{ asset('dist/plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('dist/plugins/datatables/dataTables.bootstrap4.min.js') }}"></script>
<!-- Buttons examples -->
<script src="{{ asset('dist/plugins/datatables/dataTables.buttons.min.js') }}"></script>
<script src="{{ asset('dist/plugins/datatables/buttons.bootstrap4.min.js') }}"></script>
<script src="{{ asset('dist/plugins/datatables/jszip.min.js') }}"></script>
<script src="{{ asset('dist/plugins/datatables/pdfmake.min.js') }}"></script>
<script src="{{ asset('dist/plugins/datatables/vfs_fonts.js') }}"></script>
<script src="{{ asset('dist/plugins/datatables/buttons.html5.min.js') }}"></script>
<script src="{{ asset('dist/plugins/datatables/buttons.print.min.js') }}"></script>
<script src="{{ asset('dist/plugins/datatables/buttons.colVis.min.js') }}"></script>
<!-- Responsive examples -->
<script src="{{ asset('dist/plugins/datatables/dataTables.responsive.min.js') }}"></script>
<script src="{{ asset('dist/plugins/datatables/responsive.bootstrap4.min.js') }}"></script>

<!-- Datatable init js -->
<script src="assets/pages/datatables.init.js"></script>
<script>
    $(function() {
        $("#datatable").DataTable();
    });
</script>
@endsection

resources/views/admin/transaksi/index.blade.php
@extends('backend.master')
@section('title', 'Data Transaksi')
@section('sub-judul', 'Siswa')
@section('button')

<a href="{{route('transaksi.create')}}" class="btn btn-primary waves-effect waves-light">Tambah Data</a>

@endsection

@section('content')

<div class="row">
                            <div class="col-12">
                                <div class="card m-b-20">
                                    <div class="card-body">

                                        <h4 class="mt-0 header-title"></h4>

                                        <table id="datatable" class="table table-bordered dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;">
                                            <thead>
                                            <tr>
                                                <th>Waktu</th>
                                                <th>No Induk Siswa</th>
                                                <th>Nama Siswa</th>
                                                <th>Type</th>
                                                <th>Saldo</th>
                                                <!-- <th>Action</th> -->
                                            </tr>
                                            </thead>


                                            <tbody>
                                            @foreach($siswas as $siswa)
                                            @php
                                                $total_pemasukan = 0;
                                                $total_pengeluaran = 0;
                                                $is_saving = 0;
                                                foreach($siswa->transactions as $transaction) {

                                                    $is_saving = $transaction->saving_id;

                                                    if($is_saving) $total_pemasukan += $transaction->amount;
                                                    else $total_pengeluaran += $transaction->amount;

                                                    if($is_saving==0){
                                                        $is_saving =  'Tarik';
                                                    }
                                                    else{
                                                        $is_saving = 'Setor';
                                                    }
                                            @endphp
                                            <tr>
                                                <td>{{$transaction->created_at}}</td>
                                                <td>{{$siswa->induk}}</td>
                                                <td>{{$siswa->nama}}</td>
                                                <td>{{$is_saving}}</td>
                                                <td>Rp {{number_format($transaction->amount)}}</td>
                                            </tr>
                                            @php
                                                }
                                            @endphp
                                            @endforeach
                                            </tbody>
                                        </table>

                                    </div>
                                </div>
                            </div> <!-- end col -->
                        </div>

@endsection
@section('page_css')
        <!-- DataTables -->
        <link rel="stylesheet" href="{{ asset('dist/plugins/datatables/dataTables.bootstrap4.min.css') }}">
        <link rel="stylesheet" type="text/css" href="{{ asset('dist/plugins/datatables/buttons.bootstrap4.min.css') }}"/>
                <!-- Responsive datatable examples -->
        <link href="{{ asset('dist/plugins/datatables/responsive.bootstrap4.min.css') }}" rel="stylesheet" type="text/css" />
        <script src="{{ asset('dist/assets/js/vue.js') }}"></script>
        <script src="{{ asset('dist/assets/js/accounting.min.js') }}"></script>

        <style type="text/css">
        .noline {
            display:inline;
            margin:0px;
            padding:0px;
        }
        input[type=number]::-webkit-inner-spin-button, 
        input[type=number]::-webkit-outer-spin-button { 
        -webkit-appearance: none; 
        margin: 0; 
        }
        </style>
@endsection

@section('page_js')
        <!-- DataTables -->
        <!-- Required datatable js -->
        <script src="{{ asset('dist/plugins/datatables/jquery.dataTables.min.js') }}"></script>
        <script src="{{ asset('dist/plugins/datatables/dataTables.bootstrap4.min.js') }}"></script>
        <!-- Buttons examples -->
        <script src="{{ asset('dist/plugins/datatables/dataTables.buttons.min.js') }}"></script>
        <script src="{{ asset('dist/plugins/datatables/buttons.bootstrap4.min.js') }}"></script>
        <script src="{{ asset('dist/plugins/datatables/jszip.min.js') }}"></script>
        <script src="{{ asset('dist/plugins/datatables/pdfmake.min.js') }}"></script>
        <script src="{{ asset('dist/plugins/datatables/vfs_fonts.js') }}"></script>
        <script src="{{ asset('dist/plugins/datatables/buttons.html5.min.js') }}"></script>
        <script src="{{ asset('dist/plugins/datatables/buttons.print.min.js') }}"></script>
        <script src="{{ asset('dist/plugins/datatables/buttons.colVis.min.js') }}"></script>
        <!-- Responsive examples -->
        <script src="{{ asset('dist/plugins/datatables/dataTables.responsive.min.js') }}"></script>
        <script src="{{ asset('dist/plugins/datatables/responsive.bootstrap4.min.js') }}"></script>

        <!-- Datatable init js -->
        <script src="assets/pages/datatables.init.js"></script>
        <script>
        $(function() {
            $("#datatable").DataTable();
        });
        </script>
@endsection