routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/dashboard');
});

Auth::routes([]);

Route::get('/home', function () {
    return redirect('/dashboard');
});

Route::group(['middleware' => 'auth'], function () {
    Route::get('/dashboard', 'DashboardController@index')->name('home');
    Route::get('/siswa/export_excel', 'SiswaController@export_excel')->name('siswa-export-excel');
    Route::get('/siswa/export_pdf', 'SiswaController@export_pdf')->name('siswa-export-pdf');
    Route::resource('/siswa', 'SiswaController');
    Route::resource('/kelas', 'KelasController');
    Route::get('/tabungan', 'TabunganController@index')->name('tabungan');
    Route::resource('/transaksi', 'TransaksiController');
    Route::resource('/buku', 'BukuController');
    Route::resource('/pinjaman', 'PinjamanController');
    Route::get('/transaksi/rekap', 'TabunganController@index')->name('transaksi.rekap');
    Route::get('/panduan', 'PanduanController@index')->name('panduan');
    Route::get('/profile', 'HomeController@profile')->name('profile');
    Route::get('/user', 'HomeController@user')->name('user');
    Route::post('/profile/store', 'HomeController@profile_update')->name('profile.store');

    Route::get('/user/export_pdf', 'HomeController@user_export_pdf')->name('user-export-pdf');
});

app/Siswa.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Siswa extends Model
{
    protected $guarded = [];

    public function kelas() {
    	return $this->belongsTo('App\Kelas');
    }
    
    public function savings() {
    	return $this->hasOne('App\Saving');
    }

    public function transactions() {
        return $this->hasMany('App\Transaksi','siswa_id','induk');
    }

}

app/Http/Controllers/SiswaController.php
<?php

namespace App\Http\Controllers;

use App\Siswa;
use Illuminate\Http\Request;
use App\Kelas;
use App\Exports\SiswaExport;
use Maatwebsite\Excel\Facades\Excel;
use App\Http\Controllers\Controller;
use PDF;

class SiswaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {   
        $kelas = Kelas::all();
        $data = Siswa::all();
        return view('admin.siswa.index', compact('data','kelas'));
    }
    
    public function export_excel()
	{
        return Excel::download(new SiswaExport, 'laporan-siswa'. date('Y-m-d H:i:s') .'.xlsx');
    }
    
    public function export_pdf()
	{
        $siswa = Siswa::all();

        $pdf = PDF::loadview('admin.siswa.pdf',['data'=>$siswa]);
        return $pdf->download('laporan-total-siswa-'.date('Y-m-d H:i:s').'.pdf');
	}

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {   
        $kelas = Kelas::all();
        return view('admin.siswa.add', compact('kelas'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'induk' => 'required|min:3|unique:siswas',
            'nama' => 'required',
            'kelas' => 'required',
        ]);

        $post = Siswa::create([
            'induk' => $request->induk,
            'nama' => $request->nama,
            'kelas_id' => $request->kelas,
        ]);

        return redirect()->back()->with('success', 'Postingan berhasil disimpan');
    }

    
    public function edit($id)
    {   
        $kelas = Kelas::all();
        $siswa = Siswa::findorfail($id);
        return view('admin.siswa.edit', compact('kelas','siswa'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Siswa  $siswa
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'induk' => 'min:3',
            'nama' => 'required',
            'kelas' => 'required',
        ]);

        $siswa = [
            // 'induk' => $request->induk,
            'nama' => $request->nama,
            'kelas_id' => $request->kelas,
        ];

        Siswa::whereId($id)->update($siswa);
        return redirect()->route('siswa.index')->with('success', 'Data berhasil diupdate');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Siswa  $siswa
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $siswa = Siswa::findorfail($id);
        $siswa->delete();

        return redirect()->route('siswa.index')->with('success', 'Data berhasil dihapus');
    }

    public function show()
    {
        //
    }
}

resources/views/admin/siswa/add.blade.php
@extends('backend.master')
@section('title', 'Tambah Siswa')
@section('sub-judul', 'Siswa')
@section('button')
<a href="{{route('siswa.index')}}" class="btn btn-primary waves-effect waves-light">Back</a>

@endsection
@section('content')
@if(count($errors) >0)
		@foreach($errors->all() as $error )
		<div class="alert alert-danger" role="alert">
			{{ $error }}
		</div>
		@endforeach
	@endif 

	@if(Session::has('success'))
		<div class="alert alert-info alert-dismissible fade show" role="alert">
		  <strong>{{ Session('success') }}</strong>
		  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
		    <span aria-hidden="true">&times;</span>
		  </button>
		</div>
	@endif
<div class="row">
            <div class="col-12">
                <div class="card m-b-20">
                    <div class="card-body">
                    <form action="{{route('siswa.store')}}" method="POST">
                        @csrf
                        <div class="form-group row">
                            <label for="example-text-input" class="col-sm-2 col-form-label">Nomor Identitas</label>
                            <div class="col-sm-10">
                                <input class="form-control" name="induk" type="text" value="" id="example-text-input">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="example-search-input" class="col-sm-2 col-form-label">Nama </label>
                            <div class="col-sm-10">
                                <input class="form-control" name="nama" type="text" value="" id="example-search-input">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-sm-2 col-form-label">Kelas</label>
                            <div class="col-sm-10">
                                <select class="form-control" name="kelas">
                                    <option>-- PIlih Kelas --</option>
                                @foreach($kelas as $data)
                                <option value="{{$data->id}}">{{$data->nama}}</option>
                                @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <button class="btn btn-primary btn-block">Simpan</button>
                        </div>
                        </form>
                    </div>
                </div>
            </div> <!-- end col -->
        </div>

@endsection

resources/views/admin/siswa/edit.blade.php
@extends('backend.master')
@section('title', 'Tambah Siswa')
@section('sub-judul', 'Siswa')
@section('button')
<a href="{{route('siswa.index')}}" class="btn btn-primary waves-effect waves-light">Back</a>

@endsection
@section('content')
@if(count($errors) >0)
		@foreach($errors->all() as $error )
		<div class="alert alert-danger" role="alert">
			{{ $error }}
		</div>
		@endforeach
	@endif 

	@if(Session::has('success'))
		<div class="alert alert-success alert-dismissible fade show" role="alert">
		  <strong>{{ Session('success') }}</strong>
		  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
		    <span aria-hidden="true">&times;</span>
		  </button>
		</div>
	@endif
<div class="row">
            <div class="col-12">
                <div class="card m-b-20">
                    <div class="card-body">
                    <form action="{{route('siswa.update', $siswa->id)}}" method="POST">
                        @csrf
                        @method('patch')
                        <div class="form-group row">
                            <label for="example-text-input" class="col-sm-2 col-form-label">Nomor Identitas</label>
                            <div class="col-sm-10">
                                <input disabled class="form-control" name="induk" type="text" value="{{$siswa->induk}}" id="example-text-input">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="example-search-input" class="col-sm-2 col-form-label">Nama </label>
                            <div class="col-sm-10">
                                <input class="form-control" name="nama" type="text" value="{{$siswa->nama}}" id="example-search-input">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-sm-2 col-form-label">Kelas</label>
                            <div class="col-sm-10">
                                <select class="form-control" name="kelas">
                                    <option>Pilih Kategori</option>
                                    @foreach($kelas as $data)
                                    <option value="{{$data->id}}" @if($data->id == $siswa->kelas_id)
                                        selected
                                        @endif
                                        >{{$data->nama}}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <button class="btn btn-primary btn-block">Simpan</button>
                        </div>
                        </form>
                    </div>
                </div>
            </div> <!-- end col -->
        </div>

@endsection

resources/views/admin/siswa/index.blade.php
@extends('backend.master')
@section('title', 'Data Siswa')
@section('sub-judul', 'Siswa')
@section('button')

<a href="{{route('siswa-export-pdf')}}" class="btn btn-primary waves-effect waves-light">Export PDF</a>
<a href="{{route('siswa-export-excel')}}" class="btn btn-primary waves-effect waves-light">Export Excel</a>
<a href="{{route('siswa.create')}}" class="btn btn-primary waves-effect waves-light">Tambah Data</a>
@endsection

@section('content')

<div class="row">
                            <div class="col-12">
                                <div class="card m-b-20">
                                    <div class="card-body">

                                        <h4 class="mt-0 header-title"></h4>

                                        <table id="datatable" class="table table-bordered dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;">
                                            <thead>
                                            <tr>
                                                <th>No</th>
                                                <th>No Induk Siswa</th>
                                                <th>Nama Siswa</th>
                                                <th>Kelas</th>
                                                <th>Action</th>
                                            </tr>
                                            </thead>


                                            <tbody>
                                            @foreach($data as $siswa => $hasil)
                                            <tr>
                                                <td>{{$siswa+1}}</td>
                                                <td>{{$hasil->induk}}</td>
                                                <td>{{$hasil->nama}}</td>
                                                <td>{{$hasil->kelas->nama}}</td>
                                                <td>
                                                    <form action="{{ route('siswa.destroy', $hasil->id) }}" method="POST">
                                                        @csrf
                                                        @method('delete')
                                                        <a href="{{ route('siswa.edit', $hasil->id) }}" class="btn btn-primary btn-sm">Edit</a>
                                                        <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                                                    </form>
                                                </td>
                                            </tr>
                                            @endforeach
                                            </tbody>
                                        </table>

                                    </div>
                                </div>
                            </div> <!-- end col -->
                        </div>

@endsection
@section('page_css')
        <!-- DataTables -->
        <link rel="stylesheet" href="{{ asset('dist/plugins/datatables/dataTables.bootstrap4.min.css') }}">
        <link rel="stylesheet" type="text/css" href="{{ asset('dist/plugins/datatables/buttons.bootstrap4.min.css') }}"/>
                <!-- Responsive datatable examples -->
        <link href="{{ asset('dist/plugins/datatables/responsive.bootstrap4.min.css') }}" rel="stylesheet" type="text/css" />
        <script src="{{ asset('dist/assets/js/vue.js') }}"></script>
        <script src="{{ asset('dist/assets/js/accounting.min.js') }}"></script>

        <style type="text/css">
        .noline {
            display:inline;
            margin:0px;
            padding:0px;
        }
        input[type=number]::-webkit-inner-spin-button, 
        input[type=number]::-webkit-outer-spin-button { 
        -webkit-appearance: none; 
        margin: 0; 
        }
        </style>
@endsection

@section('page_js')
        <!-- DataTables -->
        <!-- Required datatable js -->
        <script src="{{ asset('dist/plugins/datatables/jquery.dataTables.min.js') }}"></script>
        <script src="{{ asset('dist/plugins/datatables/dataTables.bootstrap4.min.js') }}"></script>
        <!-- Buttons examples -->
        <script src="{{ asset('dist/plugins/datatables/dataTables.buttons.min.js') }}"></script>
        <script src="{{ asset('dist/plugins/datatables/buttons.bootstrap4.min.js') }}"></script>
        <script src="{{ asset('dist/plugins/datatables/jszip.min.js') }}"></script>
        <script src="{{ asset('dist/plugins/datatables/pdfmake.min.js') }}"></script>
        <script src="{{ asset('dist/plugins/datatables/vfs_fonts.js') }}"></script>
        <script src="{{ asset('dist/plugins/datatables/buttons.html5.min.js') }}"></script>
        <script src="{{ asset('dist/plugins/datatables/buttons.print.min.js') }}"></script>
        <script src="{{ asset('dist/plugins/datatables/buttons.colVis.min.js') }}"></script>
        <!-- Responsive examples -->
        <script src="{{ asset('dist/plugins/datatables/dataTables.responsive.min.js') }}"></script>
        <script src="{{ asset('dist/plugins/datatables/responsive.bootstrap4.min.js') }}"></script>

        <!-- Datatable init js -->
        <script src="assets/pages/datatables.init.js"></script>
        <script>
        $(function() {
            $("#datatable").DataTable();
        });
        </script>
@endsection

resources/views/admin/siswa/pdf.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Laporan PDF Siswa</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>

	<div class="container">
		<center>
			<h4>Laporan PDF Siswa</h4>
		</center>
		<br/>
		<table class='table table-bordered'>
			<thead>
				<tr>
					<th>No</th>
					<th>No Induk</th>
					<th>Nama Siswa</th>
					<th>Kelas</th>
				</tr>
			</thead>
			<tbody>
				@php $i=1 @endphp   
				@foreach($data as $p)
				<tr>
					<td>{{ $i++ }}</td>
					<td>{{$p->induk}}</td>
					<td>{{$p->nama}}</td>
					<td>{{$p->kelas->nama}}</td>
				</tr>
				@endforeach
			</tbody>
		</table>

	</div>

</body>
</html>