routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/dashboard');
});

Auth::routes([]);

Route::get('/home', function () {
    return redirect('/dashboard');
});

Route::group(['middleware' => 'auth'], function () {
    Route::get('/dashboard', 'DashboardController@index')->name('home');
    Route::get('/siswa/export_excel', 'SiswaController@export_excel')->name('siswa-export-excel');
    Route::get('/siswa/export_pdf', 'SiswaController@export_pdf')->name('siswa-export-pdf');
    Route::resource('/siswa', 'SiswaController');
    Route::resource('/kelas', 'KelasController');
    Route::get('/tabungan', 'TabunganController@index')->name('tabungan');
    Route::resource('/transaksi', 'TransaksiController');
    Route::resource('/buku', 'BukuController');
    Route::resource('/pinjaman', 'PinjamanController');
    Route::get('/transaksi/rekap', 'TabunganController@index')->name('transaksi.rekap');
    Route::get('/panduan', 'PanduanController@index')->name('panduan');
    Route::get('/profile', 'HomeController@profile')->name('profile');
    Route::get('/user', 'HomeController@user')->name('user');
    Route::post('/profile/store', 'HomeController@profile_update')->name('profile.store');

    Route::get('/user/export_pdf', 'HomeController@user_export_pdf')->name('user-export-pdf');
});

app/Buku.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Buku extends Model
{
    protected $guarded = [];
}

app/Http/Controllers/BukuController.php
<?php

namespace App\Http\Controllers;

use App\Buku;
use App\Siswa;
use Illuminate\Http\Request;

class BukuController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $buku = Buku::all();
        $siswa = Siswa::all();
        return view('admin.buku.index', compact('buku', 'siswa'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $buku = Buku::all();
        return view('admin.buku.add', compact('buku'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'nama' => 'required',
        ]);

        $post = Buku::create([
            'nama' => $request->nama,
        ]);

        return redirect()->back()->with('success', 'Buku berhasil disimpan');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Buku  $buku
     * @return \Illuminate\Http\Response
     */
    public function show(Buku $buku)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Buku  $buku
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $buku = Buku::findorfail($id);
        return view('admin.buku.edit', compact('buku'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Buku  $buku
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'nama' => 'required',
        ]);

        $kelas = [
            // 'induk' => $request->induk,
            'nama' => $request->nama,
        ];

        Buku::whereId($id)->update($kelas);
        return redirect()->back()->with('success', 'Buku berhasil diupdate');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Buku  $buku
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $siswa = Buku::findorfail($id);
        $siswa->delete();

        return redirect()->route('buku.index')->with('success', 'Buku berhasil dihapus');
    }
}

resources/views/admin/buku/add.blade.php
@extends('backend.master')
@section('title', 'Tambah Siswa')
@section('sub-judul', 'Siswa')
@section('button')
<a href="{{route('buku.index')}}" class="btn btn-primary waves-effect waves-light">Back</a>

@endsection
@section('content')
@if(count($errors) >0)
@foreach($errors->all() as $error )
<div class="alert alert-danger" role="alert">
    {{ $error }}
</div>
@endforeach
@endif

@if(Session::has('success'))
<div class="alert alert-info alert-dismissible fade show" role="alert">
    <strong>{{ Session('success') }}</strong>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
@endif
<div class="row">
    <div class="col-12">
        <div class="card m-b-20">
            <div class="card-body">
                <form action="{{route('buku.store')}}" method="POST">
                    @csrf
                    <div class="form-group row">
                        <label for="example-search-input" class="col-sm-2 col-form-label">Nama </label>
                        <div class="col-sm-10">
                            <input class="form-control" name="nama" type="text" value="" id="example-search-input">
                        </div>
                    </div>
                    <div class="form-group">
                        <button class="btn btn-primary btn-block">Simpan</button>
                    </div>
                </form>
            </div>
        </div>
    </div> <!-- end col -->
</div>

@endsection

resources/views/admin/buku/edit.blade.php
@extends('backend.master')
@section('title', 'Edit Buku')
@section('sub-judul', 'Buku')
@section('button')
<a href="{{route('buku.index')}}" class="btn btn-primary waves-effect waves-light">Back</a>

@endsection
@section('content')
@if(count($errors) >0)
@foreach($errors->all() as $error )
<div class="alert alert-danger" role="alert">
    {{ $error }}
</div>
@endforeach
@endif

@if(Session::has('success'))
<div class="alert alert-success alert-dismissible fade show" role="alert">
    <strong>{{ Session('success') }}</strong>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
@endif
<div class="row">
    <div class="col-12">
        <div class="card m-b-20">
            <div class="card-body">
                <form action="{{route('buku.update', $buku->id)}}" method="POST">
                    @csrf
                    @method('patch')
                    <div class="form-group row">
                        <label for="example-search-input" class="col-sm-2 col-form-label">Nama </label>
                        <div class="col-sm-10">
                            <input class="form-control" name="nama" type="text" value="{{$buku->nama}}" id="example-search-input">
                        </div>
                    </div>
                    <div class="form-group">
                        <button class="btn btn-primary btn-block">Simpan</button>
                    </div>
                </form>
            </div>
        </div>
    </div> <!-- end col -->
</div>

@endsection

resources/views/admin/buku/index.blade.php
@extends('backend.master')
@section('title', 'Data Buku')
@section('sub-judul', 'Buku')
@section('button')

<a href="{{route('buku.create')}}" class="btn btn-primary waves-effect waves-light">Tambah Data</a>

@endsection

@section('content')

<div class="row">
    <div class="col-12">
        <div class="card m-b-20">
            <div class="card-body">

                <h4 class="mt-0 header-title"></h4>

                <table id="datatable" class="table table-bordered dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Nama Kelas</th>
                            <th>Action</th>
                        </tr>
                    </thead>


                    <tbody>
                        @foreach($buku as $siswa => $hasil)
                        <tr>
                            <td>{{$siswa+1}}</td>
                            <td width="80%">{{$hasil->nama}}</td>
                            <td width="20%">
                                <form action="{{ route('buku.destroy', $hasil->id) }}" method="POST">
                                    @csrf
                                    @method('delete')
                                    <a href="{{ route('buku.edit', $hasil->id) }}" class="btn btn-primary btn-sm">Edit</a>
                                    <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                                </form>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>

            </div>
        </div>
    </div> <!-- end col -->
</div>

@endsection
@section('page_css')
<!-- DataTables -->
<link rel="stylesheet" href="{{ asset('dist/plugins/datatables/dataTables.bootstrap4.min.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('dist/plugins/datatables/buttons.bootstrap4.min.css') }}" />
<!-- Responsive datatable examples -->
<link href="{{ asset('dist/plugins/datatables/responsive.bootstrap4.min.css') }}" rel="stylesheet" type="text/css" />
<script src="{{ asset('dist/assets/js/vue.js') }}"></script>
<script src="{{ asset('dist/assets/js/accounting.min.js') }}"></script>

<style type="text/css">
    .noline {
        display: inline;
        margin: 0px;
        padding: 0px;
    }

    input[type=number]::-webkit-inner-spin-button,
    input[type=number]::-webkit-outer-spin-button {
        -webkit-appearance: none;
        margin: 0;
    }
</style>
@endsection

@section('page_js')
<!-- DataTables -->
<!-- Required datatable js -->
<script src="{{ asset('dist/plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('dist/plugins/datatables/dataTables.bootstrap4.min.js') }}"></script>
<!-- Buttons examples -->
<script src="{{ asset('dist/plugins/datatables/dataTables.buttons.min.js') }}"></script>
<script src="{{ asset('dist/plugins/datatables/buttons.bootstrap4.min.js') }}"></script>
<script src="{{ asset('dist/plugins/datatables/jszip.min.js') }}"></script>
<script src="{{ asset('dist/plugins/datatables/pdfmake.min.js') }}"></script>
<script src="{{ asset('dist/plugins/datatables/vfs_fonts.js') }}"></script>
<script src="{{ asset('dist/plugins/datatables/buttons.html5.min.js') }}"></script>
<script src="{{ asset('dist/plugins/datatables/buttons.print.min.js') }}"></script>
<script src="{{ asset('dist/plugins/datatables/buttons.colVis.min.js') }}"></script>
<!-- Responsive examples -->
<script src="{{ asset('dist/plugins/datatables/dataTables.responsive.min.js') }}"></script>
<script src="{{ asset('dist/plugins/datatables/responsive.bootstrap4.min.js') }}"></script>

<!-- Datatable init js -->
<script src="assets/pages/datatables.init.js"></script>
<script>
    $(function() {
        $("#datatable").DataTable();
    });
</script>
@endsection